### PR TITLE
Size of participant, mentors and projects cards fixed

### LINKED ISSUE #362: Resize Cards
The aspect ratio of every card is not eye pleasing. Make changes so it feels even and good

### PR DESCRIPTION
**Pull request by Rattlecode17sh**
* Please fill out the template below

### Did you read the instructions in [README](../README.md) ?

Yes

### Solves which issue ?

Fixes #362 

### Give discription.

Here is the live link:- https://rattlecode17sh.github.io/Opencode-Collaborative-19/

## Checklist

(To mark the checkboxes use `x` within the box brackets)

- [x] Signed the code of conduct.

- [x] Have you added yourself to the participants.

- [x] Joined opencode zulip server.

### CODE REVIEW

**Comment by Rattlecode17sh** [comment]
screenshot 115
screenshot 114

Previously

**Comment by Rattlecode17sh** [comment]
screenshot 113
screenshot 111

Currently

**Comment by Rattlecode17sh** [comment]
@ananya-agrawal  please review

**Comment by pradeepgangwar** [comment]
LGTM

**Pull request merged**
