### PR TITLE
Fixed issue #19.

### PR DESCRIPTION
**Pull request by littleprodigy**
sort participants name in alphabetical order.

### CODE REVIEW

**Comment by Ace-Bansal** [comment]
@littleprodigy Please provide a live link.

**Comment by littleprodigy** [comment]
@Ace-Bansal sir, how to provide link

**Comment by Ace-Bansal** [comment]
1. Don't call anyone sir/ma'am on GitHub. We're both contributors to open-source :D.
2. Go to your fork of the repo on GitHub.
3. Go to settings.
4. Scroll down to the section 'Github Pages'.
5. In the source option, select 'master branch' from the dropdown menu.
6. Hit save.
7. Scroll down once again and you'll find a url. This url is your live link of the project.
8. Feel free to ask any doubts that you may have in this process.

**Comment by littleprodigy** [comment]
Actually, I have tried to solve but participants name is not showing as mentors name is showing .
link :  https://littleprodigy.github.io/Opencode-Collaborative-19/ but problem is not solved yet.

**Comment by Tlazypanda** [comment]
@littleprodigy You have an error in sort function -
`return a.name.toLowerCase() > b.nametoLowerCase();`

b.name.toLowerCase() is the correct syntax.Kindly look into this and if you run into further issues feel free to ping :smile:

**Comment by littleprodigy** [comment]
Ok, will do it, thanks for information.

**Comment by ananya-agrawal** [comment]
@littleprodigy is the issue solved? Names are not coming in sorted order on the link you shared.

**Comment by Ace-Bansal** [comment]
Inactive PR.

**Pull request closed without merging**
