### PR TITLE
List all issues from all projects fixes #245

### LINKED ISSUE #245: list issues of all projects in the websites in a new section
With the help of github API, make a new section titled issues in which you can see all the open issues of a particular repo in OpenCode19.
Something like : https://opencode18.github.io/OpenCode-Collaborative/

### PR DESCRIPTION
**Pull request by anupm12**
* Please fill out the template below

### Did you read the instructions in [README](../README.md) ?

Yes

### Solves which issue ?

Solves #245 

### Give discription.

Fetching data from GitHub API.

## Checklist

(To mark the checkboxes use `x` within the box brackets)

- [x] Signed the code of conduct.

- [x] Have you added yourself to the participants.

- [x] Joined opencode zulip server.

### CODE REVIEW

**Comment by ananya-agrawal** [comment]
@anupm12 live link please

**Comment by anupm12** [comment]
@ananya-agrawal 
Live link 
https://list-all-issues.netlify.com/

**Comment by ananya-agrawal** [comment]
@anupm12 the frontend is not similar to the other parts of page, try something else nah 
though yeah you implemented it quite well :raised_hands:

**Comment by ananya-agrawal** [comment]
@zerefwayne @pradeepgangwar reviews required :stuck_out_tongue:

**Comment by anupm12** [comment]
@ananya-agrawal Ok will change frontend 😃

**Comment by ananya-agrawal** [comment]
yeah why are you making it black. why not let the background stay white only as it will look similar to the entire page, and moreover i was thinking why not list the projects in a sequence rather then in random fashion as it is making the section look a bit fussy 
what are you planning to do with it?

**Comment by anupm12** [comment]
I thought of making two columns with buttons.
Is that on click sliding thing ok?

**Comment by ananya-agrawal** [comment]
yeah that sliding thing is good, and did you hardcode all the projects?
Like is it listing all the projects or projects with open issues only?

**Comment by anupm12** [comment]
It is listing only the open issues

**Comment by ananya-agrawal** [comment]
Did you hardcode all the projects? Like consider there is a project let suppose collaborative website itself, but at the moment having 0 issues opened, so will it still list the website or not?

**Comment by anupm12** [comment]
@ananya-agrawal I have changed the frontend also made it work fine with the night mode

**Comment by ananya-agrawal** [comment]
Chage bg of the sliding thing also, entire webpage is white and it being black looks weird

**Comment by anupm12** [comment]
@ananya-agrawal I have changed the background to white
Please review.
@Anupam-dagar @pradeepgangwar @Ace-Bansal @zerefwayne @aswinzz @shreyanshdwivedi

**Comment by anupm12** [comment]
Live link
https://list-all-issues.netlify.com/

**Comment by Anupam-dagar** [comment]
@anupm12 the implementation is great although there are still some rough edges left. Check the screenshot, the yellow border of button don't have a proper left margin from borders and the two rows of cards don't have spacing between them. In some cases I found out that cards itself are of different heights which disturb the orientation.
screenshot from 2019-01-31 21-36-35

**Comment by anupm12** [comment]
I have opened a new pr
Please review it.
Sorry for the inconvenience.

**Pull request closed without merging**
