### PR TITLE
landing page

### PR DESCRIPTION
**Pull request by vishnuk7**
https://ecstatic-jang-f7838d.netlify.com/

### CODE REVIEW

**Comment by prateek76** [comment]
@vishnuk7 Follow proper pr format

**Comment by prateek76** [comment]
Add issue number in description

**Comment by pradeepgangwar** [comment]
@vishnuk7 Which issue are you trying to solve? Please add issue number in description.

**Comment by pradeepgangwar** [comment]
Closing as duplicate of #162 . Feel free to open this with a new issue for better design after if #162 gets merged.

**Comment by pradeepgangwar** [comment]
Closing as duplicate of #162 . Feel free to open this with a new issue for better design after if #162 gets merged.

**Pull request closed without merging**
