### PR TITLE
Add devgupta2607 as participant

### PR DESCRIPTION
**Pull request by devgupta2607**

### CODE REVIEW

**Comment by aswinzz** [comment]
@devgupta2607 Resolve the merge conflicts

**Comment by Ace-Bansal** [comment]
@devgupta2607 Please respond else this PR will be closed tomorrow.

**Comment by pradeepgangwar** [comment]
@devgupta2607 Also add your image. You have referenced it but there is no images uploaded.

**Comment by Ace-Bansal** [comment]
Inactive PR.

**Pull request closed without merging**
