### PR TITLE
Fixes #320: Add a reading progress bar to the page

### LINKED ISSUE #320: Add a reading progress bar to the page

### PR DESCRIPTION
**Pull request by thenullterminator**
* Please fill out the template below

### Did you read the instructions in [README](../README.md) ?

Yes

### Solves which issue ?

Fixes #320 

### Give discription.
I have implemented reading progress bar using jqeury. To justify presence of progress bar I have also embedded trailer inside the page instead of having a button in the nav bar. Since jquery is not supported  on github. I am adding few screenshots as well as live link to checkout the page layout.  

LIVELINK: https://thenullterminator.github.io/OC19/

## Checklist

(To mark the checkboxes use `x` within the box brackets)

- [x] Signed the code of conduct.

- [x] Have you added yourself to the participants.

- [x] Joined opencode zulip server.

### CODE REVIEW

**Comment by thenullterminator** [comment]
screenshot from 2019-02-02 22-51-20
screenshot from 2019-02-02 22-51-23
screenshot from 2019-02-02 22-51-26
screenshot from 2019-02-02 22-51-30
screenshot from 2019-02-02 22-51-32

**Comment by prateek76** [comment]
@thenullterminator wait! what jquery is not supported on github 😑

**Comment by prateek76** [comment]
@ananya-agrawal is embedding trailer inside the page needed? please help him in jquery part

**Comment by thenullterminator** [comment]
https://www.i-programmer.info/news/167-javascript/12017-github-removes-jquery-why.html

**Pull request closed without merging**
