### PR TITLE
#202 Compress images of participants, mentors, and projects

### PR DESCRIPTION
**Pull request by anupm12**
All the images are now below 800-900kb.

### CODE REVIEW

**Comment by pradeepgangwar** [comment]
@anupm12 I dont see any change in participants image.

**Comment by anupm12** [comment]
I have compressed 10 images from participants folder that were exceeding 1mb.

**Comment by anupm12** [comment]
screenshot_20190118-130530
Please have a look at this screenshot @pradeepgangwar

**Comment by pradeepgangwar** [comment]
@anupm12 That's fine. I thought there are more such images.

**Pull request merged**
