### PR TITLE
Solved text moving out of card in mobile view fixes #287

### LINKED ISSUE #287: When viewed in mobile view text goes out of the cards.
screenshot 45

### PR DESCRIPTION
**Pull request by anupm12**
* Please fill out the template below

### Did you read the instructions in [README](../README.md) ?

Yes

### Solves which issue ?

fixes #287 

### Give discription.

Text is now properly aligned in the card also fixed image.

## Checklist

(To mark the checkboxes use `x` within the box brackets)

- [x] Signed the code of conduct.

- [x] Have you added yourself to the participants.

- [x] Joined opencode zulip server.

### CODE REVIEW

**Comment by ananya-agrawal** [comment]
@anupm12 please provide a live link

**Comment by anupm12** [comment]
@ananya-agrawal 
Live link
https://responsive-card.netlify.com/

**Comment by ananya-agrawal** [comment]
PR is also having changes that makes 6 cards come instead of four :stuck_out_tongue:

**Comment by anupm12** [comment]
I'm sorry if I was not supposed to do that 😅

**Comment by anupm12** [comment]
@ananya-agrawal Is this ok or should I make changes?

**Comment by ananya-agrawal** [comment]
@anupm12 oh sorry by mistake I was looking in a fork which wasn't updated so misunderstood that the pr for 6 participants is still not merged. Sorry for this, you dont need to remove that, that was my bad :sweat_smile:

**Pull request merged**
