### PR TITLE
Added myself to participant.json

### PR DESCRIPTION
**Pull request by Rajatsharma1007**

### CODE REVIEW

**Comment by aswinzz** [comment]
@Rajatsharma1007 please upload an image and add its url

**Comment by Rajatsharma1007** [comment]
@aswinzz  I have resolved the conflict

**Comment by Anupam-dagar** [comment]
@Rajatsharma1007 please remove the pull request template, that issue is assigned to someone else.

**Comment by Rajatsharma1007** [comment]
@Anupam-dagar  I have removed the pull request template

**Comment by Anupam-dagar** [comment]
@Rajatsharma1007 looks like you haven't signed the code of conduct. I would request you to do so. Also please don't @ mention mentors unless its been 36 hours without review. These all things are written in the code of conduct. Please abide by them. We already get the notification when any changes happen on the PR, @ mentioning just create spammy notification over it.

**Comment by Anupam-dagar** [comment]
Thanks for your contribution :tada:

**Pull request merged**
