### PR TITLE
Update participants.json

### PR DESCRIPTION
**Pull request by thesmallstar**
Added name.

### CODE REVIEW

**Comment by zerefwayne** [comment]
@thesmallstar Did you find any way of checking if the image exists or not?

**Comment by thesmallstar** [comment]
@zerefwayne working on it.

**Comment by thesmallstar** [comment]
@zerefwayne  Please verify the changes.

**Comment by thesmallstar** [comment]
@zerefwayne  Both the type of errors are fixed now: 
url: https://thesmallstar.github.io/Opencode-Collaborative-19-1/

**Pull request merged**
