### PR TITLE
Image size fix in mobile view for projects cards

### LINKED ISSUE #338: Image size is not in same ratio in mobile view for project cards
screenshot_2019-01-29-04-24-25-622

### PR DESCRIPTION
**Pull request by Rattlecode17sh**
* Please fill out the template below

### Did you read the instructions in [README](../README.md) ?

Yes

### Solves which issue ?

Fixes #338 

### Give discription.

Image size in mobile view for project cards is fixed now

## Checklist

(To mark the checkboxes use `x` within the box brackets)

- [x] Signed the code of conduct.

- [x] Have you added yourself to the participants.

- [x] Joined opencode zulip server.

### CODE REVIEW

**Comment by prateek76** [comment]
live link?

**Comment by Rattlecode17sh** [comment]
https://rattlecode17sh.github.io/Opencode-Collaborative-19/

**Comment by Rattlecode17sh** [comment]
@prateek76 please review

**Comment by Rattlecode17sh** [comment]
screenshot 81
Here is the card which was causing error last time

**Comment by Rattlecode17sh** [comment]
52162295-af387080-26f7-11e9-954d-65bc2a7de1ae
In previous case

**Comment by prateek76** [comment]
in iphoneX and other smaller views

**Comment by Rattlecode17sh** [comment]
okay

**Comment by Rattlecode17sh** [comment]
screenshot 82
screenshot 84
@prateek76 have a look i think now it looks fine

**Comment by Rattlecode17sh** [comment]
@ananya-agrawal  please review. As told by @prateek76 it is almost done

**Comment by prateek76** [comment]
gnd2

**Comment by Rattlecode17sh** [comment]
screenshot 87
@prateek76  check it now

**Comment by pradeepgangwar** [comment]
LGTM @ananya-agrawal @prateek76

**Pull request merged**
