### PR TITLE
Add hover effect to footer icon fixes #344

### LINKED ISSUE #344: Add hover effect to footer icons
Add hover effect similar to that of cards to icons in footer.

### PR DESCRIPTION
**Pull request by anupm12**
* Please fill out the template below

### Did you read the instructions in [README](../README.md) ?

Yes

### Solves which issue ?

Fixes #344 

### Give discription.

[Write Here. Be Specific]

## Checklist

(To mark the checkboxes use `x` within the box brackets)

- [x] Signed the code of conduct.

- [x] Have you added yourself to the participants.

- [x] Joined opencode zulip server.

### CODE REVIEW

**Comment by anupm12** [comment]
Live link 
https://musing-hermann-c1b8d4.netlify.com/

**Comment by anupm12** [comment]
@ananya-agrawal please review

**Comment by ananya-agrawal** [comment]
@anupm12 haha this was creative, though I was thinking to make the icons become bold when hovered on. Try hovering on the fb, github, twitter icon of the backside of participants cards

**Comment by anupm12** [comment]
@ananya-agrawal done

**Comment by anupm12** [comment]
@prateek76  please review

**Comment by anupm12** [comment]
@prateek76 I have given 1.5 scale as of now
Shall I reduce it to 1.2 or should it be even less than that?

**Comment by prateek76** [comment]
#347 i left a comment there

**Comment by anupm12** [comment]
@prateek76 ok.

**Comment by prateek76** [comment]
@anupm12 resolve the conflicts

**Pull request merged**
