### PR TITLE
Clickable logo fixes #333

### LINKED ISSUE #333: Make logo and name on navbar clickable
This issue was approved by @ananya-agrawal 

image

### PR DESCRIPTION
**Pull request by anupm12**
* Please fill out the template below

### Did you read the instructions in [README](../README.md) ?

Yes

### Solves which issue ?

Fixes #333 

### Give discription.

[Write Here. Be Specific]

## Checklist

(To mark the checkboxes use `x` within the box brackets)

- [x] Signed the code of conduct.

- [x] Have you added yourself to the participants.

- [x] Joined opencode zulip server.

### CODE REVIEW

**Comment by prateek76** [comment]
@anupm12 remove last commit from this pr

**Comment by anupm12** [comment]
@prateek76 how do I do that?

**Comment by anupm12** [comment]
Both of those commits are from different branches.
The last commit is merged so even if I do fetch upstream and again there will be no changes.
Help me out @prateek76

**Comment by prateek76** [comment]
https://stackoverflow.com/questions/36168839/how-to-remove-commits-from-a-pull-request this may help

**Comment by prateek76** [comment]
@anupm12 You can try rebasing , there you can pick and drop the commits you want

**Comment by anupm12** [comment]
Done @prateek76

**Pull request merged**
