### PR TITLE
Added favicon

### PR DESCRIPTION
**Pull request by ashish4321**
* Please fill out the template below

### Did you read the instructions in [README](../README.md) ?

>Yes

### Solves which issue ?

>Solves #244 

### Added IIITA logo as a favicon

>[Write Here. Be Specific]

## Checklist

(To mark the checkboxes use `x` within the box brackets)

- [x ] Signed the code of conduct.

- [ x] Have you added yourself to the participants.

- [ x] Joined opencode zulip server.

### CODE REVIEW

**Comment by Jigar3** [comment]
Provide live link

**Comment by ashish4321** [comment]
https://ashish4321.github.io/Opencode-Collaborative-19/

**Comment by ashish4321** [comment]
https://ashish4321.github.io/Opencode-Collaborative-19/

**Comment by ashish4321** [comment]
@Ace-Bansal Changed favicon

**Comment by ashish4321** [comment]
@Ace-Bansal @Anupam-dagar Can you please review it?

**Pull request merged**
