### PR TITLE
fixes issue #103

### LINKED ISSUE #103: Improve the projects card design and flip cards.
image

The font sizes and spacing are not appropriate. Checkout the Bootstrap4 Docs and see how cards are designed.

### PR DESCRIPTION
**Pull request by ujjwal-batra**
* Please fill out the template below

### Did you read the instructions in [README](../README.md) ?

Yes

### Solves which issue ?

Fixes #103

### Give discription.

[fixes the card flip issue of project cards. now when we hover on the cards about, mentors and tech stacks get displayed]

## Checklist

(To mark the checkboxes use `x` within the box brackets)

- [x] Signed the code of conduct.

- [x] Have you added yourself to the participants.

- [x] Joined opencode zulip server.

### CODE REVIEW

**Comment by ujjwal-batra** [comment]
live link : https://ujjwal-batra.github.io/Opencode-Collaborative-19/

**Comment by ujjwal-batra** [comment]
@ananya-agrawal mam should i add a default image on the back or its good like this??

**Comment by ujjwal-batra** [comment]
@ananya-agrawal mam done

**Comment by ananya-agrawal** [comment]
@ujjwal-batra sorry for the delay. Fix merge conflicts rest LGTM

**Comment by ujjwal-batra** [comment]
@ananya-agrawal mam done ....but what to do with issue #250

**Comment by ujjwal-batra** [comment]
@ananya-agrawal mam conflicts resolved

**Comment by ananya-agrawal** [comment]
@ujjwal-batra I am merging this pr for issue #103 and reducing its points back to 20 as only flipping of cards is done
and for issue #250 let me know if you want to work on else you may just unclaim it and it will get reassigned to someone else.

**Comment by ujjwal-batra** [comment]
@ananya-agrawal mam i will do issue #250

**Comment by ananya-agrawal** [comment]
Don't use mam on github :sweat_smile:

**Comment by ujjwal-batra** [comment]
@ananya-agrawal okay 😁

**Pull request merged**
