### PR TITLE
Fixes #248(Embed trailer in website)

### LINKED ISSUE #248: Embed the OpenCode19 Trailer in the website
Make a link in the navbar titled trailer, on clicking it a modal should open which plays the opencode trailer
https://www.facebook.com/opencodeiiita/videos/2301796573173119/

### PR DESCRIPTION
**Pull request by Archies11**
* Please fill out the template below

### Did you read the instructions in [README](../README.md) ?

Yes

### Solves which issue ?

Fixes #248

### Give discription.

I have made the modal using the link provided but I am facing certain ambiguities in the sizing of the same.

## Checklist

(To mark the checkboxes use `x` within the box brackets)

- [x] Signed the code of conduct.

- [x] Have you added yourself to the participants.

- [x] Joined opencode zulip server.

### CODE REVIEW

**Comment by Archies11** [comment]
Live link: https://archies11.github.io/Opencode-Collaborative-19/
the issue with the sizing is now sorted:)

**Comment by Archies11** [comment]
> navbar and footer looks distorted and also you need to overwrite bootstrap css for modal @Archies11

How do I overwrite a bootstrap css file?Couldn't find any fruitful resources so as to understand the procedure for the same. :sweat_smile:

**Comment by prateek76** [comment]
@Archies11 use !important

**Comment by Archies11** [comment]
@ananya-agarwal 
LIVE LINK: https://archies11.github.io/Opencode-Collaborative-19/
:smile: :smiley:

**Pull request merged**
