### PR TITLE
update participants.json

### PR DESCRIPTION
**Pull request by Neelabh46**

### CODE REVIEW

**Comment by pradeepgangwar** [comment]
@Neelabh46 Please add ur pic and also add your block carefully following the indentation.

**Comment by shreyanshdwivedi** [comment]
@Neelabh46 please resolve conflicts too

**Comment by Ace-Bansal** [comment]
@Neelabh46 You have specified an imageurl but haven't added an image. Either add an image or if you don't wish to include your image for any reason then leave please leave the imageurl blank.

**Comment by Neelabh46** [comment]
> please
Have a look if there is any other issue left

**Pull request merged**
