### PR TITLE
Issue #16 Make cards for mentors

### PR DESCRIPTION
**Pull request by nucelya**
Added a hover effect for mentor card

### CODE REVIEW

**Comment by zerefwayne** [comment]
@nucelya Please provide a live link.

**Comment by prateek76** [comment]
@nucelya provide github page link and add issue number in description

**Comment by nucelya** [comment]
> @nucelya Please provide a live link.

@zerefwayne can u plz explain how to do it??

**Comment by pradeepgangwar** [comment]
@nucelya Any update? Please rebase the branch and update the PR.

**Pull request closed without merging**
