### PR TITLE
Fixes #248(Modal for Trailer)

### LINKED ISSUE #248: Embed the OpenCode19 Trailer in the website
Make a link in the navbar titled trailer, on clicking it a modal should open which plays the opencode trailer
https://www.facebook.com/opencodeiiita/videos/2301796573173119/

### PR DESCRIPTION
**Pull request by Archies11**
### Did you read the instructions in [README](../README.md) ?

>Yes

### Solves which issue ?

>Solves #248

### Give discription.

>Added a modal that plays the trailer of opencode 19 when 'trailer' tab is clicked on in the navbar

## Checklist

(To mark the checkboxes use `x` within the box brackets)

- [x] Signed the code of conduct.

- [x] Have you added yourself to the participants.

- [x] Joined opencode zulip server.

### CODE REVIEW

**Comment by prateek76** [comment]
@Archies11 it's opening in https://archies11.github.io/Opencode-Collaborative-19/vendor/video.html
open it in the same page as modal

**Comment by Archies11** [comment]
Same page as in should i add the code of file video.html(that contains the modal with the trailer) in the index.html?

**Comment by Archies11** [comment]
I did as asked and copied the code in index.html with proper syntax and linking but instead of preloader, I am seeing the modal i have created. Please guide me through any mistakes I have made.

**Comment by Archies11** [comment]
> @Archies11 Implement it according to bootstrap modal documentation
> 
> reference - https://www.w3schools.com/bootstrap/bootstrap_modal.asp

Okay, will try this.

**Comment by Archies11** [comment]
new PR: https://github.com/opencodeiiita/Opencode-Collaborative-19/pull/321

**Pull request closed without merging**
