### PR TITLE
Custom scroll bar added

### LINKED ISSUE #366: Add a custom scroll bar

### PR DESCRIPTION
**Pull request by Rattlecode17sh**
* Please fill out the template below

### Did you read the instructions in [README](../README.md) ?

Yes

### Solves which issue ?

Fixes #366 

### Give discription.

Custom scroll bar added in the website

## Checklist

(To mark the checkboxes use `x` within the box brackets)

- [x] Signed the code of conduct.

- [x] Have you added yourself to the participants.

- [x] Joined opencode zulip server.

### CODE REVIEW

**Comment by Rattlecode17sh** [comment]
Live link:- https://rattlecode17sh.github.io/Opencode-Collaborative-19/

**Comment by Rattlecode17sh** [comment]
@ananya-agrawal please review

**Comment by sourabh1031** [comment]
@Rattlecode17sh sorry to review as a participant but this does not work on firefox and edge browsers as far as i know , i tried on my browser

**Comment by Rattlecode17sh** [comment]
Yeah that's because i used webkit scrollbar and it does not support IE and firefox

**Comment by Rattlecode17sh** [comment]
It does not support IE

**Comment by prateek76** [comment]
> @Rattlecode17sh sorry to review as a participant but this does not work on firefox and edge browsers as far as i know , i tried on my browser

you can review pr @sourabh1031, it's good to understand the project

**Comment by Rattlecode17sh** [comment]
So what to do now @prateek76 .. As i used webkit scrollbar and it does not support IE

**Pull request closed without merging**
