### PR TITLE
#issue 57 solved

### LINKED ISSUE #57: Make participant cards flipped on click
Add "about" to come on the backside of card when flipped

### PR DESCRIPTION
**Pull request by Rattlecode17sh**
Fixes #57

### CODE REVIEW

**Comment by ananya-agrawal** [comment]
@Rattlecode17sh please provide a live link

**Comment by Rattlecode17sh** [comment]
Here is the live link generated

https://rattlecode17sh.github.io/Opencode-Collaborative-19/

**Comment by ananya-agrawal** [comment]
@Rattlecode17sh can we remove the extra blank space coming in the front side of card? and there are commits related to loader getting mixed in this pr. Try making a separate branch and then work, for now remove those commits from this pr.
@pradeepgangwar @zerefwayne reviews please

**Comment by pradeepgangwar** [comment]
@Rattlecode17sh Text is also getting flipped please avoid that. We need something like this https://pragmaconf.tech/speakers.html. Nice try btw! 😄

**Comment by ananya-agrawal** [comment]
screenshot from 2019-01-16 22-58-59
screenshot from 2019-01-16 23-01-36

there are some minor issue, do fix them also.

**Comment by Rattlecode17sh** [comment]
Give me some time. I will do it by tomorrow

**Comment by Rattlecode17sh** [comment]
I need one more day to figure out the problem.

**Pull request closed without merging**
