### PR TITLE
center aligned the header

### PR DESCRIPTION
**Pull request by kavi-12**
* Please fill out the template below

### Did you read the instructions in [README](../README.md) ?
yes

>Yes/No

### Solves which issue ?
alignment of header #118 

>Solves #[issue number]

### Give discription.
aligned the heading open code 19 to center

>[Write Here. Be Specific]

## Checklist

(To mark the checkboxes use `x` within the box brackets)

- [ ] Signed the code of conduct.

- [x ] Have you added yourself to the participants.

- [ ] Joined opencode zulip server.

### CODE REVIEW

**Comment by aswinzz** [comment]
@kavi-12 Provide live link so that we can review it.

**Comment by aswinzz** [comment]
Also resolve merge conflicts

**Comment by kavi-12** [comment]
https://kavi-12.github.io/Opencode-Collaborative-19/
 #227

**Comment by aswinzz** [comment]
@kavi-12 this issue was not assigned to you. So closing the PR.

**Comment by kavi-12** [comment]
https://kavi-12.github.io/Opencode-Collaborative-19/
#118

**Pull request closed without merging**
