### PR TITLE
participant games card fixes #342

### LINKED ISSUE #342: Make cards for participant's games
Make a new section for participant's games and add all the games made in #204 in cards under the section.
A parallel issue to add all the games in the json file is opened so the one working on the issue need not to add all the games in the json also. 
Link to json file for games: https://github.com/opencodeiiita/Opencode-Collaborative-19/blob/master/data/games.json

### PR DESCRIPTION
**Pull request by anupm12**
* Please fill out the template below

### Did you read the instructions in [README](../README.md) ?

Yes

### Solves which issue ?

Fixes #342 

### Give discription.

[Write Here. Be Specific]

## Checklist

(To mark the checkboxes use `x` within the box brackets)

- [x] Signed the code of conduct.

- [x] Have you added yourself to the participants.

- [x] Joined opencode zulip server.

### CODE REVIEW

**Comment by anupm12** [comment]
@ananya-agrawal @prateek76 please review.

**Comment by prateek76** [comment]
@anupm12 also add itch.io icon 
icon link - https://itch.io/press-kit
also games card icon scaling and transition time looks good apply same in other pr

**Comment by anupm12** [comment]
@prateek76 ok

**Comment by prateek76** [comment]
@anupm12 don't add itch icon for now

**Pull request merged**
