### PR TITLE
Issue #60, sorted participants

### PR DESCRIPTION
**Pull request by techac**
Solves Issue #60

### CODE REVIEW

**Comment by ananya-agrawal** [comment]
@techac please provide live link

**Comment by ananya-agrawal** [comment]
@techac please provide live link

**Comment by Tlazypanda** [comment]
@techac In case you need help with providing the link-
1.Open your fork of the repo on GitHub.
2.Open settings tab.
3.Scroll down to the section 'Github Pages'.
4.In the source option, select 'master branch' from the dropdown menu.
5.Hit save.
6.It will update and provide you with a url. This url is your live link of the project.

Incase you run into any issues feel free to ping :smile: 
Also if you are finding it difficult to resolve conflicts let us know

**Comment by pradeepgangwar** [comment]
@techac please update the PR.

**Comment by pradeepgangwar** [comment]
Closing this PR due to inactivity and marking the issue open.

**Pull request closed without merging**
