### PR TITLE
Update index.html. Fix Issue #3

### PR DESCRIPTION
**Pull request by devgupta2607**

### CODE REVIEW

**Comment by devgupta2607** [comment]
@zerefwayne How do I provide a live link ?

**Comment by zerefwayne** [comment]
@devgupta2607 Go to your repo's settings and enable github pages and paste the link here.

**Comment by devgupta2607** [comment]
There has been some problem operating git and commit. So I am trying to learn git first

**Comment by ananya-agrawal** [comment]
@devgupta2607 still you need to provide a live link so that the changes you made can be verified.

**Comment by pradeepgangwar** [comment]
@devgupta2607  Please respond to the PR. Also this PR contains redundant changes that do not correspond to this issue #3

**Comment by pradeepgangwar** [comment]
@zerefwayne close this PR and reassign the issue.

**Pull request closed without merging**
