### PR TITLE
Fixed issue #11 

### PR DESCRIPTION
**Pull request by shivhek25**
> Added GitHub, facebook and twitter links through icons
> Banished .DS_Store

### CODE REVIEW

**Comment by zerefwayne** [comment]
@shivhek25 Please provide a live link with your PRs.

**Comment by shivhek25** [comment]
@zerefwayne Do you mean the ".github.io" link ? Some other project is already live, can I send a screenshot instead ?

**Comment by prateek76** [comment]
@shivhek25 change the branch for now in github pages, remove it after review

**Comment by prateek76** [comment]
> @prateek76 I have made a separate branch to fix the issue and fixed the code. How do I make my version of the webpage live on Github pages ?

Go to github pages in settings of your cloned repo and change to branch you used for making this pr

**Comment by shivhek25** [comment]
@prateek76 Under the "Select Source" section, I have the option to only select master branch or none

**Comment by prateek76** [comment]
> @prateek76 Under the "Select Source" section, I have the option to only select master branch or none

Go to https://opencodeiiita.slack.com, solution is given there by @zerefwayne

**Comment by shivhek25** [comment]
Thank you for your help.  @prateek76 
The live link is : https://shivhek25.github.io/Opencode-Collaborative-19/
@zerefwayne

**Pull request merged**
