### PR TITLE
Image size in mobile view is not in same ratio

### LINKED ISSUE #338: Image size is not in same ratio in mobile view for project cards
screenshot_2019-01-29-04-24-25-622

### PR DESCRIPTION
**Pull request by Rattlecode17sh**
* Please fill out the template below

### Did you read the instructions in [README](../README.md) ?

Yes

### Solves which issue ?

Fixes #338 

### Give discription.

Image size is now fixed

## Checklist

(To mark the checkboxes use `x` within the box brackets)

- [x] Signed the code of conduct.

- [x] Have you added yourself to the participants.

- [x] Joined opencode zulip server.

### CODE REVIEW

**Comment by Rattlecode17sh** [comment]
Here is the live link :- https://rattlecode17sh.github.io/Opencode-Collaborative-19/

**Comment by Rattlecode17sh** [comment]
screenshot 63

Here are the project cards after changes

**Comment by Rattlecode17sh** [comment]
@ananya-agrawal please review

**Comment by ananya-agrawal** [comment]
@Rattlecode17sh any updates on this?

**Comment by Rattlecode17sh** [comment]
Just give me one day...half way completed

**Pull request closed without merging**
