### PR TITLE
solves issue #103

### PR DESCRIPTION
**Pull request by ujjwal-batra**
live link: https://ujjwal-batra.github.io/Opencode-Collaborative-19/

### CODE REVIEW

**Comment by ananya-agrawal** [comment]
@ujjwal-batra write a proper description of what all changes you did and the issue that will be solved by this pr as fixes:[issue number]

**Comment by ujjwal-batra** [comment]
@ananya-agrawal actually mam i had  done that on purpose so that the text on the image do not get reversed....this is why i turned the image 360 deg and the bottom to 180deg

**Comment by ujjwal-batra** [comment]
@ananya-agrawal ok mam i will correct it

**Comment by ananya-agrawal** [comment]
@ujjwal-batra status?

**Pull request closed without merging**
