### PR TITLE
Issue #16 make cards for mentor

### PR DESCRIPTION
**Pull request by nucelya**
live link 
https://nucelya.github.io/Opencode-Collaborative-19/

### CODE REVIEW

**Comment by nucelya** [comment]
there is a slight problem in live link, 
it is showing mentor cards twice 
cards with design diff than participants cards are made by me

**Comment by pradeepgangwar** [comment]
@nucelya This looks good to me. Please check why cards are appearing twice. @Anupam-dagar @ananya-agrawal @Ace-Bansal @zerefwayne Please check.

**Comment by Tlazypanda** [comment]
@nucelya You have hardcoded the cards for all the mentors so a reason why they are appearing twice maybe because there's a hardcoded version by you and another that is taking from the json feed.So just try to display it from the json feed itself by adding all your styling to that.If you are still unsure how to proceed feel free to ping :smile:

**Comment by Ace-Bansal** [comment]
Inactive PR.

**Pull request closed without merging**
