### PR TITLE
Add Cod3Creator to Participants

### PR DESCRIPTION
**Pull request by Cod3Creator**

### CODE REVIEW

**Comment by Ace-Bansal** [comment]
@Cod3Creator Please resolve the merge conflicts.

**Comment by Cod3Creator** [comment]
Conflict resolved.

**Comment by Cod3Creator** [comment]
@Ace-Bansal Please review the request.I have made changes.

**Comment by Ace-Bansal** [comment]
line 30. You've entered your github handle in some other participant's object.

**Comment by Cod3Creator** [comment]
@Ace-Bansal I have made necessary changes.Kindly review.

**Pull request closed without merging**
