### PR TITLE
Fixes #320: Add a reading progress bar to the page

### LINKED ISSUE #320: Add a reading progress bar to the page

### PR DESCRIPTION
**Pull request by thenullterminator**
* Please fill out the template below

### Did you read the instructions in [README](../README.md) ?

Yes

### Solves which issue ?

Fixes #320 

### Give discription.
In order to justify presence of reading progress bar I have emmbedded trailer (so that content of web page increases).
Check out: https://thenullterminator.github.io/oc19/

## Checklist

(To mark the checkboxes use `x` within the box brackets)

- [x] Signed the code of conduct.

- [x] Have you added yourself to the participants.

- [x] Joined opencode zulip server.

### CODE REVIEW

**Comment by thenullterminator** [comment]
Also modified pagination to fix overlapping issue.(shown below)
screenshot from 2019-02-03 17-39-30
screenshot from 2019-02-03 17-39-46

**Comment by thenullterminator** [comment]
@prateek76  Done!

**Comment by prateek76** [comment]
erse
dont't make any change in modal fix it as it was before @thenullterminator

**Comment by thenullterminator** [comment]
@prateek76 Done!

**Pull request merged**
