### PR TITLE
add name to participants.json

### PR DESCRIPTION
**Pull request by sourabh1031**

### CODE REVIEW

**Comment by Ace-Bansal** [comment]
@sourabh1031 Your PR removes the other participants.

**Comment by sourabh1031** [comment]
@Ace-Bansal actually i didn't pull the changes from master of upstrem in my local copy before pushing my changes to my fork. That is why merge confiict happened. Please tell me how to resolve this further

**Comment by ananya-agrawal** [comment]
@sourabh1031 https://help.github.com/articles/resolving-a-merge-conflict-on-github/

**Comment by sourabh1031** [comment]
@ananya-agrawal actually i have resolved merge conflict from my cli then again it is showing the same. Why it is happening again?

**Comment by ananya-agrawal** [comment]
@sourabh1031 still facing problem?

**Comment by sourabh1031** [comment]
@ananya-agrawal yes i have commented above my problem

**Comment by sourabh1031** [comment]
@Ace-Bansal i think you were asking me to add  comma which have fixed

**Pull request merged**
