### PR TITLE
Added scroll to top button

### PR DESCRIPTION
**Pull request by ashish4321**
#85  Fixed

### CODE REVIEW

**Comment by ashish4321** [comment]
@ananya-agrawal  Please Review the PR

**Comment by zerefwayne** [comment]
@ashish4321 Please resolve conflicts.

**Comment by ashish4321** [comment]
@zerefwayne Resolved

**Comment by prateek76** [comment]
> @zerefwayne Resolved

still conflicts are there, please resolve them

**Comment by prateek76** [comment]
@ashish4321 Please provide live link (Github page link)

**Comment by ashish4321** [comment]
https://ashish4321.github.io/Opencode-Collaborative-19/

**Comment by ashish4321** [comment]
okk

**Pull request merged**
