### PR TITLE
Fixed issue #15 (made cards for participants)

### PR DESCRIPTION
**Pull request by mohammed-adil**
Fixed issue #15 (made cards for participants) by adding card layouts for each participant, and added social media links of each participant.

### CODE REVIEW

**Comment by zerefwayne** [comment]
@mohammed-adil Please provide a live link and screenshots.

**Comment by mohammed-adil** [comment]
I did in Issues comment section, but nobody replied over there!
pic

BTW blank space is due to missing images!
Link: https://mohammed-adil.github.io/Opencode-Collaborative-19/index.html

**Comment by mohammed-adil** [comment]
@prateek76 Images aren't of same dimensions, I had to use object-fit and  object-position to position the images.
Any suggestions for it?
I can make cards of fixed size.

**Comment by prateek76** [comment]
> @prateek76 Images aren't of same dimensions, I had to use object-fit and object-position to position the images.
> Any suggestions for it?
> I can make cards of fixed size.

you can try height: auto for mobile devices, also try for different devices.

if needed implement media queries using this [https://www.w3schools.com/css/css3_mediaqueries_ex.asp](https://www.w3schools.com/css/css3_mediaqueries_ex.asp)

**Comment by mohammed-adil** [comment]
If I set the images to auto, some of the images height's are pretty big and that'll take the whole card size!
And I do know about the media queries, but only if the images where of similar size than I could've implemented a better card UI

**Comment by prateek76** [comment]
@mohammed-adil here card is breaking  

screenshot from 2019-01-13 01-59-32

**Comment by mohammed-adil** [comment]
> 575px

hey @prateek76 here's how the screen will look like if i remove the max-height 
screenshot_2019-01-13 opencode 2019 collaborative
Is it ok?

**Comment by mohammed-adil** [comment]
@prateek76 i fixed the card breaking issue, by adding extra height when the screen size is reduced to 756px, but it also makes other cards have a blank space. Although i can make it particularly for only the cards which has lot of extra texts!

**Comment by mohammed-adil** [comment]
> 
> 
> > @prateek76 i fixed the card breaking issue, by adding extra height when the screen size is reduced to 756px, but it also makes other cards have a blank space. Although i can make it particularly for only the cards which has lot of extra texts!
> 
> push the changes, can you explain what happened with the last image?
@prateek76 hey all of changes you mentioned are completed. Please have a look
https://mohammed-adil.github.io/Opencode-Collaborative-19/index.html

**Comment by prateek76** [comment]
@mohammed-adil LGTM! nice work dude. only some images have height problem

**Comment by Ace-Bansal** [comment]
LGTM for now. We can create new issues for improving design and showing the font-awesome icons only if the social links are provided later on. @zerefwayne thoughts?

**Comment by prateek76** [comment]
@mohammed-adil  just update your description with issue number and squash your commits to get it merged

**Comment by mohammed-adil** [comment]
> 
> 
> @mohammed-adil just update your description with issue number and squash your commits to get it merged

Hey @prateek76 can you help me out with squashing commits?, from past 29 mins I'm stuck over here!, don't know which commit to pick and squash because I see all other participants commit also. Don't know how to squash only my commits.

**Pull request merged**
