### PR TITLE
solved issue #103

### LINKED ISSUE #103: Improve the projects card design and flip cards.
image

The font sizes and spacing are not appropriate. Checkout the Bootstrap4 Docs and see how cards are designed.

### PR DESCRIPTION
**Pull request by ujjwal-batra**
screenshot 39

fixes #103

### CODE REVIEW

**Comment by ujjwal-batra** [comment]
live link : https://ujjwal-batra.github.io/Opencode-Collaborative-19/

**Comment by pradeepgangwar** [comment]
@ujjwal-batra I don't see any specific improvement. Can you try changing design of cards.

**Comment by ujjwal-batra** [comment]
@pradeepgangwar ok sir let me check some changes that i can do

**Comment by ujjwal-batra** [comment]
@ananya-agrawal mam i was thinking of that but it will be same as opencode 18 website

**Comment by ananya-agrawal** [comment]
@ujjwal-batra yeah sure. I will increase points for the issue :+1:

**Comment by ujjwal-batra** [comment]
@ananya-agrawal ok mam tq

**Comment by ananya-agrawal** [comment]
@ujjwal-batra updates?

**Comment by ujjwal-batra** [comment]
@ananya-agrawal mam shiuld i close  this pr and make a new one?? i already solved it and just need to resolve few conflicts

**Comment by ananya-agrawal** [comment]
@ujjwal-batra your choice. either fix conflicts or open a new pr, but please be a bit fast to do this as because of this issue still being on working state new issues related to cards are on hold

**Comment by ujjwal-batra** [comment]
@ananya-agrawal ok mam i will submit another pr in 2 hrs ..

**Pull request closed without merging**
