### PR TITLE
Created landing page in reference to issue #35

### LINKED ISSUE #35: Create a landing page.
The current landing page looks too plain. Make an aesthetic looking landing page for the website.
Do a google search for good looking landing pages. For reference, take a look at https://opencodeiiita.github.io
opencode 2019 collaborative 12-01-2019 16-30-49

### PR DESCRIPTION
**Pull request by mohammed-adil**
Created landing page for issue #35. For now its just header section, I would've completed the rest of the page if the mentors had responded to my earlier comment in issues(comment section).

Fixes #35

### CODE REVIEW

**Comment by pradeepgangwar** [comment]
@mohammed-adil Design looks good to me. Let me oping other mentors for their review. Let's wrap it up ASAP. :)

**Comment by pradeepgangwar** [comment]
@zerefwayne @Anupam-dagar @aswinzz Please take a look.

**Comment by mohammed-adil** [comment]
> 
> 
> @mohammed-adil Design looks good to me. Let me oping other mentors for their review. Let's wrap it up ASAP. :)

Ahh thanks a lot, I thought no one will see this PR

**Comment by pradeepgangwar** [comment]
Hahaha @mohammed-adil it's not like that. Mentors will review rhe PRs whenever they have time..

**Comment by Tlazypanda** [comment]
@mohammed-adil LGTM :+1: @Anupam-dagar Kindly review.

**Pull request merged**
