### PR TITLE
Toggle switch for a night mode fixes #249

### LINKED ISSUE #249: Toggle switch for a night mode

### PR DESCRIPTION
**Pull request by anupm12**
* Please fill out the template below

### Did you read the instructions in [README](../README.md) ?

>Yes

### Solves which issue ?

>Solves #249 

### Give discription.

>Added a toggle button in navbar for night mode.

## Checklist

(To mark the checkboxes use `x` within the box brackets)

- [x] Signed the code of conduct.

- [x] Have you added yourself to the participants.

- [x] Joined opencode zulip server.

### CODE REVIEW

**Comment by anupm12** [comment]
Live link https://opencode-night-mode.netlify.com

**Comment by Jigar3** [comment]
Toggling on the night mode makes the landing page image to disappear and go black. Make it not do that. You could replace that image with a dark background image.

**Comment by anupm12** [comment]
Ok.
Will do it today.

**Comment by anupm12** [comment]
Ok will try that out and let you know

**Comment by anupm12** [comment]
@Jigar3 I have changed the background.
Please check it out
Live link  https://opencode-night-mode.netlify.com

**Comment by anupm12** [comment]
@Jigar3  I apologize.
I forgot to uncomment the spinner.
Fixed it in the last commit.

**Comment by anupm12** [comment]
@prateek76 Please review this pr

**Comment by prateek76** [comment]
@anupm12 resolve the conflicts

**Comment by anupm12** [comment]
@prateek76 done resolving conflicts

**Comment by anupm12** [comment]
@prateek76 If everything is fine then please merge this

**Comment by prateek76** [comment]
@anupm12 please add padding between toggle button and fork count

**Comment by anupm12** [comment]
@prateek76 done changes

**Comment by anupm12** [comment]
> @anupm12 please add padding between toggle button and fork count else everything looks fine, nice work 👍

@prateek76 
I had to solve conflicts and add padding only because you first merged the pr that was done after my pr.
If you reviewed my code then you might have clearly seen that I added padding to the toggle that I made, whereas the other guy did not. But as you merged the other pr first I had to again add padding which the other guy must have done to his code. Please don't take me wrong. Excuse me if I'm wrong.

**Comment by prateek76** [comment]
nah-it-can
@anupm12

**Pull request merged**
